"""Initial import

Revision ID: 4454bd628e92
Revises: 2c970f5ee5c8
Create Date: 2015-11-29 20:31:37.495012

"""

# revision identifiers, used by Alembic.
revision = '4454bd628e92'
down_revision = '2c970f5ee5c8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_layouts',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.PickleType(), nullable=False),
    sa.Column('layoutcategory', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['layoutcategory'], ['core_layouts_categories.key'], name='fk_layouts_categories', use_alter=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('core_layouts_categories',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_layouts_categories')
    op.drop_table('core_layouts')
    ### end Alembic commands ###
